env:
  browser: true
  es2021: true
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
ignorePatterns:
  - "src/assets/**/*"
extends:
  - "eslint-config-gergoszaszvaradi"
rules:
  no-extend-native: off
settings:
  react:
    version: detect